### PR TITLE
My little changes

### PR DESCRIPTION
**Pull request by mstavrin**
Hi Espen, 
These are the Numpy reference style changes I did so far to the cellsim16popsParams.py.
I thought to send you this pull request, just to see if they are enough or I should read more on this. There are some things to be added when there is a definition of class, that I need to go into the code more. This is more easy way to go that I did so far. 
Let me know how I can contribute to this. 
Maria

### CODE REVIEW

**Comment by espenhgn** [comment]
Hi Maria, 

Thanks, but this may have to wait a bit as I said, because the github files are now out of sync versus our ongoing development files in the bebiservice.umb.no http://bebiservice.umb.no/-hosted repository. I have to update the github files before I take any pull requests. But keep in mind your changes (they will not disappear when you merge my updated into your fork), it looks good. 

And please make no mention/addition or whatever of our main simulation files in messages, because it is all public. 

I’ll write you when I have it in place. 

Espen

**Comment by mstavrin** [comment]
Ok!

Best regards,
Maria

Maria L. Stavrinou
Postdoc at Computational Neuroscience Group
Institute of Mathematical Sciences and Technology
Norwegian University of Life Sciences, Ås, Norway
http://compneuro.umb.no
Int. Tel. 0047 - 6496 5225
personal web-site: https://sites.google.com/site/marialstavrinou/

**Comment by espenhgn** [comment]
Hi, 
I will not be able to commit anything today, as I ended up having issues with my NEURON installation.

Sorry!

Espen

**Comment by mstavrin** [comment]
Hi Espen,
I received this email saying closed: Anything I should do or wait for further notice?
Best regards,
Maria

Maria L. Stavrinou
Postdoc at Computational Neuroscience Group
Institute of Mathematical Sciences and Technology
Norwegian University of Life Sciences, Ås, Norway
http://compneuro.umb.no
Int. Tel. 0047 - 6496 5225
personal web-site: https://sites.google.com/site/marialstavrinou/

**Pull request closed without merging**
